# Generated by Django 5.2.7 on 2025-10-29 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='owner_name',
            field=models.CharField(default='Неизвестно', max_length=100, verbose_name='Имя владельца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='owner_phone',
            field=models.CharField(default='', max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(verbose_name='Дата и время приёма'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pet',
            field=models.CharField(max_length=100, verbose_name='Имя питомца'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='veterinarian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinic.veterinarian', verbose_name='Ветеринар'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='clinic.appointment', verbose_name='Приём'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(max_length=100, verbose_name='Дозировка'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.TextField(verbose_name='Название препарата'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='side_effects',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Побочные эффекты'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Кличка'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='clinic.owner', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(max_length=50, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вес (кг)'),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='speciality',
            field=models.CharField(max_length=100, verbose_name='Специальность'),
        ),
    ]
