# Generated by Django 5.2.6 on 2025-11-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_appointment_owner_name_appointment_owner_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
